X5C Provisioner: add example on how to restrict issued cert to signing cert Subject
smallstep/docs pull request #125
Opened 2022-08-09 09:34 UTC by Slamdunk

See https://github.com/smallstep/certificates/pull/827

2022-08-16 17:16 UTC, tashian requested changes
Hi @Slamdunk, thank you for the PR on this.
I've suggested some specific changes.

Also, please update this PR to follow the convention of [semantic linefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

Thanks!

2022-08-16 17:16 UTC, tashian commented on src/pages/docs/step-ca/provisioners.mdx
> +    signing certificate's one within templates by accessing the `.AuthorizationCrt` variable.
```
By default, the `X5C` provisioner will issue a certificates for <strong>any</strong> Subject names.
If you want to limit or modify the subject names this provisioner will issue,
you can use a <a href="/docs/step-ca/templates">certificate template</a>.
```

2022-08-16 17:16 UTC, tashian commented on src/pages/docs/step-ca/provisioners.mdx
> +    `X5C` ssh template as follow to allow SSH certificates only for `foo@bar.com` and `foo`:
```
For example, say your users will use the X5C provisioner to exchange an X.509 client certificate for an SSH user certificate.
The X.509 client certificate has `alice@example.com` as its subject,
and you want to ensure the SSH certificate has both `alice` and `alice@example.com` as principals.
The following template will make that scenario possible:
```

2022-08-16 17:16 UTC, tashian commented on src/pages/docs/step-ca/provisioners.mdx
> +            {{ replace "@bar.com" "" .AuthorizationCrt.Subject.CommonName | toJson }},
```
{{ replace "@example.com" "" .AuthorizationCrt.Subject.CommonName | toJson }},
```

2022-08-22 08:29 UTC, Slamdunk commented
> I've suggested some specific changes.

Implemented, thank you



> Also, please update this PR to follow the convention of [semantic linefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

As a non-native English speaker, honestly I have no idea how to adapt to it.
The examples in the link provided look exactly the same to me :shrug:

2022-08-22 17:05 UTC, tashian commented
lgtm. Thanks @Slamdunk!

2022-08-22 17:05 UTC, merged