Add note about potential lockouts when configuring a policy
smallstep/docs pull request #168
Opened 2022-11-18 15:26 UTC by hslatman

2022-11-22 00:52 UTC, tashian requested changes
I've just changed the capitalization to match what's on the Remote Management section of the Provisioners doc. Otherwise lgtm!

2022-11-22 00:52 UTC, tashian commented on src/pages/docs/step-ca/policies.mdx
> +    The authentication scheme for Remote Management uses short-lived X.509 certificates to authenticate (super) admin users.
```suggestion
    The authentication scheme for Remote Management uses short-lived X.509 certificates to authenticate Admin and Super Admin users.
```

2022-11-22 00:52 UTC, tashian commented on src/pages/docs/step-ca/policies.mdx
> +    When an admin requests access when an X.509 policy is active, the policy must allow the subject of the admin, or else the admin won't be able to sign in.
```suggestion
    When an Admin requests access when an X.509 policy is active, the policy must allow the subject of the Admin, or else the Admin won't be able to sign in.
```

2022-11-22 00:52 UTC, tashian commented on src/pages/docs/step-ca/policies.mdx
> +    The policy can then be adjusted to include the (super) admin subject(s), e.g. <Code>step ca policy authority x509 allow dns step</Code>.
```suggestion
    The policy can then be adjusted to include the Admin subject(s), e.g. <Code>step ca policy authority x509 allow dns step</Code>.
```

2022-11-23 21:52 UTC, hslatman commented
Committed your suggestions. Thanks! 🙂

2022-11-23 22:15 UTC, tashian approved these changes

2022-11-23 22:15 UTC, merged