Document asn.1 encoding functions
smallstep/docs pull request #210
Opened 2023-04-20 22:14 UTC by tashian

2023-04-20 22:31 UTC, maraino requested changes

2023-04-20 22:31 UTC, maraino commented on step-ca/templates.mdx
> +  {"id": "1.2.3.4", "critical": true, "value": {{ asn1Enc "int:3848281" | toJson }}}
Usually critical will be `false` on custom extensions. If the client/server does not understand that extension it should fail.
```suggestion
  {"id": "1.2.3.4", "critical": false, "value": {{ asn1Enc "int:3848281" | toJson }}}
```

2023-04-20 22:31 UTC, maraino commented on step-ca/templates.mdx
> +3. `ans1Seq` wil get all the base64 strings, decode them, create an ASN.1 SEQENCE and return the base64 of the SEQUENCE.
```suggestion
3. `asn1Seq` will get all the base64 strings, decode them, create an ASN.1 SEQENCE and return the base64 of the SEQUENCE.
```

2023-04-20 22:31 UTC, maraino commented on step-ca/templates.mdx
> +4. Finally, `toJson` returns a JSON string representation of the base64
`asn1Set` is not described.

2023-04-20 22:31 UTC, maraino commented on step-ca/templates.mdx
> +A data type can be supplied inline.
It supports the types described in [this function](https://github.com/smallstep/crypto/blob/878092791d7e5ef8530dfa949cfe3cde61373d77/x509util/extensions.go#L486):
* int: "int:1234"
* oid: "oid:1.2.3.4"
* utf8: "utf8:string"
* ia5: "ia5:srtring"
* numeric: "numeric:1234"
* printable: "printable:string" or just "string"
* utc: "utc:2023-03-29T02:03:57Z" or "utc:2023-04-20 15:28:27.909088 -0700 PDT"
* generalized: "generalized:2023-03-29T02:03:57Z" or "generalized:2023-04-20 15:28:27.909088 -0700 PDT"
* raw: a special one that allows any base64 string

2023-04-20 22:31 UTC, maraino commented on step-ca/templates.mdx
> +The data types are listed in the [`encoding/asn1` package documentation](https://pkg.go.dev/encoding/asn1)
The second parameter is not required and it will use Go's default transformation.

2023-04-25 16:17 UTC, tashian commented
Hi @maraino could I get a final review on this one? Thanks

2023-04-25 17:11 UTC, maraino requested changes
Just a typo

2023-04-25 17:11 UTC, maraino commented on step-ca/templates.mdx
> +3. `asn1Seq` gets the resulting Base64 strings, decodes them, creates an ASN.1 SEQENCE, and returns the Base64 of the SEQUENCE.
```suggestion
3. `asn1Seq` gets the resulting Base64 strings, decodes them, creates an ASN.1 SEQUENCE, and returns the Base64 of the SEQUENCE.
```

2023-04-25 17:11 UTC, maraino commented on step-ca/templates.mdx
> +- **numeric**: "numeric:01 02 03345" (multiple space-separated ints)
It allows numbers and spaces, you can also use numeric:1234, you don't have to use spaces.

2023-04-25 18:30 UTC, maraino approved these changes

2023-04-25 18:30 UTC, merged