Add basic Nebula provisioner info
smallstep/docs pull request #48
Opened 2022-02-08 18:54 UTC by tashian

2022-02-09 17:47 UTC, tashian commented
I could also say something like "this is an experimental feature that requires the use of `step ca beta` commands and a database-backed provisioner configuration". But we don't have any intro written up about `step ca beta`.

2022-02-17 18:30 UTC, maraino requested changes

2022-02-17 18:30 UTC, maraino commented on src/pages/docs/step-ca/provisioners.mdx
> +Nebula | ✔️  | ✔️  | ✔️  | ✔️  | ✔️  | 𝗫 | 𝗫 | 𝗫 | 𝗫
For SSH we are currently only allowing Host certificates.

2022-02-17 23:27 UTC, maraino approved these changes
LGTM.

Nebula certs have one `Name` and a list of `IPs`. The name is the name of the certificate, it's not a SAN, but it is usually a hostname; and nebula tools only allow setting one IP, more than one might not be supported, but look at all of them.

By default, you can create a certificate where the SANs/Principals match the Name and/or the IPs. And as all the certificate is available in templates you can use generate SANs from any other field if you control the template.

See https://github.com/slackhq/nebula/blob/b5b9d33ee753b510b316f15b503ecb11209fdf9b/cert/cert.go#L36-L45
```golang
type NebulaCertificateDetails struct {
	Name      string
	Ips       []*net.IPNet
	Subnets   []*net.IPNet
	Groups    []string
	NotBefore time.Time
	NotAfter  time.Time
	PublicKey []byte
	IsCA      bool
	Issuer    string


	// Map of groups for faster lookup
	InvertedGroups map[string]struct{}
}
```

2022-05-26 20:35 UTC, merged