Add instructions for manually creating a CRL
smallstep/docs pull request #50
Opened 2022-02-15 19:33 UTC by tashian

2022-02-15 20:39 UTC, maraino requested changes
Just a few details. 

At some point we should implement something like `step crl create`, it's not hard to do.

2022-02-15 20:39 UTC, maraino commented on src/pages/docs/step-ca/certificate-authority-server-production.mdx
> +                  ["http://crl.example.com/crl/ca.crl.pem"]
The `DER` format is more common here, just name the file `ca.crl`

2022-02-15 20:39 UTC, maraino commented on src/pages/docs/step-ca/certificate-authority-server-production.mdx
> +  ```json
GitHub prints this better if you use yaml here.

2022-02-15 20:39 UTC, maraino commented on src/pages/docs/step-ca/certificate-authority-server-production.mdx
> +      -out intermediate.crl
You named this before ca.crl

2022-02-15 22:19 UTC, maraino approved these changes
LGTM, but you haven't explained how to use the index.txt

2022-02-16 19:09 UTC, tashian commented
Good point @maraino, I've just added a small bit about how to revoke a certificate

2022-02-16 19:11 UTC, maraino approved these changes
lgtm

2022-02-16 19:15 UTC, merged